package authetication

/***********************************
authentication login status is keep in database, each record will hold user ID, login time stamp, and released hash key
Hash key is generated by server side when client login request success
Hash key will keep by client as access token; each time client send request needed to attach with the access token (hash key)
Common practice to attach hash key is by using cookies OR URL parameter
************************************/

import (
	"database/sql"
	"strings"
	"time"
)

const (
	//AnonymousID anonymous user ID
	AnonymousID = 0
	//x cookieKey   = "gorilla-goweb"
)

//Login try register user to login session if
//1. username and password matched
//2. no one is login
//return: login result, hash key, exception error message
func Login(db *sql.DB, username, password string) (bool, string, error) {
	accInfo, err := GetAccountByName(db, username)
	if err != nil {
		return false, "", err
	}

	if accInfo == nil {
		return false, "", err //no username found in database
	}

	if strings.Compare(accInfo.SaltedPwd, password) == 0 {
		now := time.Now()

		hashKey, err := RegisterLoginSession(db, accInfo, now)
		if err != nil {
			return false, "", err
		}
		/*
			//pass unique ID to cookie
			//NOTE: memory cookies can set by not providing value to property 'Expires'
			cookie := http.Cookie{
				Name:    cookieKey,
				Value:   hashKey,
				Expires: now.Add(time.Hour * 2), //expire after 2 hours
			}
			http.SetCookie(*w, &cookie)
		*/
		return true, hashKey, nil
	}

	return false, "", nil //password not match
}

//Logout try end user login session
func Logout(db *sql.DB, hashKey string) (bool, error) {

	loginSession, err := GetLoginSessionByHashKey(db, hashKey)
	if err != nil {
		return false, err
	}

	if loginSession == nil {
		return true, nil
	} else if loginSession.IsStillActive() {
		//TODO: update login session to expired
		if err = EndLoginSessionByHashKey(db, hashKey); err != nil {
			return false, err
		}
	}

	return true, nil //login session already logout
}

//GetCurrentUser get current active session's user ID
//anonymous user will return nil object
func GetCurrentUser(db *sql.DB, hashKey string) (*AccountInfo, error) {
	/*
		cookie, _ := r.Cookie(cookieKey)
		if cookie == nil {
			//cookie not found; either timeout or logged out
			return nil, nil
		}
	*/

	loginSession, err := GetLoginSessionByHashKey(db, hashKey)
	if err != nil {
		return nil, err //encounter  error
	}

	if loginSession == nil {
		return nil, nil //record not found (virtually not login yet)
	}

	if loginSession.IsStillActive() {
		return GetAccountByID(db, loginSession.AccountID)
	}

	return nil, nil //login session already been logged out
}
